"""Add difficulty_notes to problems

Revision ID: 50399a6920d7
Revises: 035482d07aeb
Create Date: 2026-08-22 09:54:42.194871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50399a6920d7'
down_revision: Union[str, Sequence[str], None] = '035482d07aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('difficulty_notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'difficulty_notes')
    # ### end Alembic commands ###
